version: '3.7'
# DevelopMent
services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./src:/myfolder/src
      - ./assets:/myfolder/assets
    environment:
      - TZ=Asia/Seoul
