version: '3.7'
# DevelopMent
services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./src:/myfolder/src
    # env_file:
    #   - ./.env
    environment:
      - TZ=Asia/Seoul
