name: KJH_NAS
######### master branch에 push 되었을때만 실행#########
on:
  push:
    branches:
      - master
######### master branch에 push 되었을때만 실행#########
jobs:
  KJH-Nas-ssh-action:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: SSH Remote
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 3000
          timeout: 40s # 30초 기본
          script: |
            echo "테스트 출력"
